const fs = require('fs');
const path = require('path');

const srcDir = path.join(__dirname, 'src');
const pluginsDir = path.join(srcDir, 'plugins');
const outputFile = path.join(__dirname, 'theme.css');
const manifestFile = path.join(__dirname, 'manifest.json');

function getVersion() {
  try {
    const manifest = JSON.parse(fs.readFileSync(manifestFile, 'utf8'));
    return manifest.version || '0.0.0';
  } catch {
    return '0.0.0';
  }
}

function getHeader() {
  const version = getVersion();
  const timestamp = new Date().toISOString().slice(0, 19).replace('T', ' ');
  return `/*
 * @name Delightful
 * @description A joyous, neo-brutalist theme built on the Delightful Design System.
 * @author Kyle Snavely
 * @version ${version}
 * @built ${timestamp}
 */

/* ==========================================================================
   DELIGHTFUL DESIGN SYSTEM - AUTO-GENERATED THEME
   Do not edit this file directly. Edit the modular files in src/
   ========================================================================== */

`;
}

function buildTheme() {
  // Core modules: src/*.css sorted numerically (00-, 01-, etc.)
  const coreFiles = fs.readdirSync(srcDir)
    .filter(file => file.endsWith('.css'))
    .sort();

  // Plugin modules: src/plugins/*.css sorted alphabetically
  let pluginFiles = [];
  if (fs.existsSync(pluginsDir)) {
    pluginFiles = fs.readdirSync(pluginsDir)
      .filter(file => file.endsWith('.css'))
      .sort();
  }

  let compiledCSS = getHeader();

  // Compile core modules
  coreFiles.forEach(file => {
    const filePath = path.join(srcDir, file);
    const content = fs.readFileSync(filePath, 'utf8').trim();
    if (content) {
      compiledCSS += `/* --- Module: ${file} --- */\n\n`;
      compiledCSS += content;
      compiledCSS += '\n\n';
    }
  });

  // Compile plugin modules
  if (pluginFiles.length > 0) {
    compiledCSS += `/* ==========================================================================
   PLUGIN OVERRIDES
   ========================================================================== */\n\n`;

    pluginFiles.forEach(file => {
      const filePath = path.join(pluginsDir, file);
      const content = fs.readFileSync(filePath, 'utf8').trim();
      if (content) {
        compiledCSS += `/* --- Plugin: ${file} --- */\n\n`;
        compiledCSS += content;
        compiledCSS += '\n\n';
      }
    });
  }

  fs.writeFileSync(outputFile, compiledCSS, 'utf8');

  const totalModules = coreFiles.length + pluginFiles.length;
  const lines = compiledCSS.split('\n').length;
  console.log(`Compiled ${totalModules} modules (${coreFiles.length} core + ${pluginFiles.length} plugins) into theme.css (${lines} lines)`);
}

// Watch mode: --watch flag
if (process.argv.includes('--watch')) {
  console.log('Watching src/ for changes...');
  buildTheme();

  const debounce = {};
  function watchHandler(dir) {
    return (eventType, filename) => {
      if (!filename || !filename.endsWith('.css')) return;
      clearTimeout(debounce[filename]);
      debounce[filename] = setTimeout(() => {
        console.log(`\nChanged: ${filename}`);
        buildTheme();
      }, 100);
    };
  }

  fs.watch(srcDir, watchHandler(srcDir));
  if (fs.existsSync(pluginsDir)) {
    fs.watch(pluginsDir, watchHandler(pluginsDir));
  }
} else {
  buildTheme();
}
